'use strict';
const express=require('express');const pool=require('../db');const auth=require('../middleware/auth');const {validateListing,transition,calculateImpact}=require('../domain/marketplaceWorkflow');const router=express.Router();router.use(auth);
async function member(c,t,u){if(!t){const e=new Error('x-tenant-id is required');e.status=400;throw e;}const q=await c.query('SELECT role FROM marketplace_memberships WHERE tenant_id=$1 AND user_id=$2 AND active=true',[t,u]);if(!q.rows[0]){const e=new Error('tenant access denied');e.status=403;throw e;}return q.rows[0].role;}const h=f=>async(req,res)=>{try{await f(req,res);}catch(e){res.status(e.status||(e.code==='23505'?409:400)).json({error:e.message});}};
router.get('/listings',h(async(req,res)=>{const t=req.header('x-tenant-id');await member(pool,t,req.user.id);const q=await pool.query('SELECT id,state,version,listing,created_at,updated_at FROM governed_listings WHERE tenant_id=$1 ORDER BY updated_at DESC LIMIT 100',[t]);res.json({listings:q.rows});}));
router.post('/listings',h(async(req,res)=>{const t=req.header('x-tenant-id'),key=req.header('idempotency-key');if(!key)throw new Error('idempotency-key is required');const data=validateListing(req.body),c=await pool.connect();try{await c.query('BEGIN');await member(c,t,req.user.id);const q=await c.query(`INSERT INTO governed_listings(tenant_id,state,listing,idempotency_key,created_by) VALUES($1,'draft',$2,$3,$4) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[t,data,key,req.user.id]);await c.query(`INSERT INTO marketplace_events(tenant_id,listing_id,actor_id,event_type,payload) VALUES($1,$2,$3,'created',$4) ON CONFLICT DO NOTHING`,[t,q.rows[0].id,req.user.id,{idempotencyKey:key}]);await c.query('COMMIT');res.status(201).json(q.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}));
router.post('/listings/:id/transition',h(async(req,res)=>{const t=req.header('x-tenant-id'),c=await pool.connect();try{await c.query('BEGIN');const role=await member(c,t,req.user.id),q=await c.query('SELECT * FROM governed_listings WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,t]);if(!q.rows[0]){const e=new Error('listing not found');e.status=404;throw e;}const row=q.rows[0];if(Number(req.body.version)!==row.version){const e=new Error('version conflict');e.status=409;throw e;}const record={...row.listing,...req.body.evidence};const next=transition(row.state,req.body.state,role,record,req.body.note);const u=await c.query('UPDATE governed_listings SET state=$1,listing=$2,version=version+1,updated_at=NOW() WHERE id=$3 RETURNING *',[next,record,row.id]);await c.query('INSERT INTO marketplace_events(tenant_id,listing_id,actor_id,event_type,payload) VALUES($1,$2,$3,$4,$5)',[t,row.id,req.user.id,'transition',{from:row.state,to:next,note:req.body.note||null}]);await c.query('COMMIT');res.json(u.rows[0]);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}));
router.post('/listings/:id/impact',h(async(req,res)=>{const t=req.header('x-tenant-id');await member(pool,t,req.user.id);const q=await pool.query('SELECT listing FROM governed_listings WHERE id=$1 AND tenant_id=$2',[req.params.id,t]);if(!q.rows[0]){const e=new Error('listing not found');e.status=404;throw e;}if(!req.body.factorVersion)throw new Error('factorVersion is required');const avoidedKgCo2e=calculateImpact(q.rows[0].listing.materials,req.body.factors||{});const saved=await pool.query('INSERT INTO impact_calculations(tenant_id,listing_id,factor_version,avoided_kg_co2e,inputs,calculated_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[t,req.params.id,req.body.factorVersion,avoidedKgCo2e,{materials:q.rows[0].listing.materials,factors:req.body.factors},req.user.id]);res.status(201).json(saved.rows[0]);}));
router.post('/listings/:id/provider-requests',h(async(req,res)=>{const t=req.header('x-tenant-id'),role=await member(pool,t,req.user.id);if(!['seller','moderator','tenant_admin'].includes(role)){const e=new Error('provider request denied');e.status=403;throw e;}if(!['identity','escrow','shipping','maps','messaging'].includes(req.body.provider))throw new Error('unsupported provider');const q=await pool.query(`INSERT INTO marketplace_outbox(tenant_id,listing_id,provider,payload,status,requested_by) VALUES($1,$2,$3,$4,'pending',$5) RETURNING *`,[t,req.params.id,req.body.provider,req.body.payload||{},req.user.id]);res.status(202).json(q.rows[0]);}));
module.exports=router;
