BEGIN;
CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS marketplace_memberships(tenant_id TEXT NOT NULL,user_id BIGINT NOT NULL,role TEXT NOT NULL CHECK(role IN('buyer','seller','moderator','safety_officer','tenant_admin')),active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS governed_listings(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('draft','moderation','listed','rejected','offer_accepted','withdrawn','escrow_pending','funded','cancelled','in_transit','delivered','disputed','refunded','settled')),version INTEGER NOT NULL DEFAULT 1,listing JSONB NOT NULL CHECK(jsonb_typeof(listing)='object'),idempotency_key TEXT NOT NULL,created_by BIGINT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS marketplace_events(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,listing_id BIGINT NOT NULL REFERENCES governed_listings(id),actor_id BIGINT NOT NULL,event_type TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}',occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS marketplace_outbox(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,listing_id BIGINT NOT NULL REFERENCES governed_listings(id),provider TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('pending','processing','succeeded','failed','dead_letter')),attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,payload JSONB NOT NULL DEFAULT '{}',requested_by BIGINT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS impact_calculations(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,listing_id BIGINT NOT NULL REFERENCES governed_listings(id),factor_version TEXT NOT NULL,avoided_kg_co2e NUMERIC(14,4) NOT NULL,inputs JSONB NOT NULL,calculated_by BIGINT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(listing_id,factor_version));
CREATE INDEX IF NOT EXISTS marketplace_listing_state_idx ON governed_listings(tenant_id,state);CREATE INDEX IF NOT EXISTS marketplace_outbox_status_idx ON marketplace_outbox(status,created_at);
COMMIT;
